import type { Metadata } from 'next'
import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
} from 'next/font/google'
import './globals.css'

import { cookies } from 'next/headers'

import { Hero } from '@/components/common/Hero'
import { SingIn } from '@/components/common/SingIn'
import { Copyright } from '@/components/common/Copyright'
import { UserProfile } from '@/components/common/UserProfile'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
})

export const metadata: Metadata = {
  title: 'NLW Spacetime',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const isAuth = cookies().has('token')

  return (
    <html lang="pt-br">
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} bg-gray-900 font-sans text-gray-100`}
      >
        <main className="min-h-screen lg:grid lg:grid-cols-2">
          <div className="relative hidden flex-col items-start justify-between overflow-hidden border-r border-white/10 bg-stars bg-cover px-28 py-16 lg:flex">
            <div className="absolute right-0 top-1/2 h-[288px] w-[526px] -translate-y-1/2 translate-x-1/2 rounded-full bg-purple-700 opacity-50 blur-full" />

            <div className="absolute bottom-0 right-2 top-0 w-2 bg-stripes" />

            {!isAuth ? <SingIn /> : <UserProfile />}
            <Hero />
            <Copyright />
          </div>

          <div className="flex flex-col bg-stars bg-cover p-16">{children}</div>
        </main>
      </body>
    </html>
  )
}
